### ISSUE TITLE
scheduled task not présent

### ISSUE THREAD

**Issue by jmthia** [HardenAD/SecureAD#118]
**Describe the bug**
I am using the master branch of Harden AD, in order to use GUI task sequence selector. After running all sequence except AD functionnel level, administration account, laps and activated AHD-TS-local-admin-groups, HAD-TS-Reset-computer-sddl.
The task scheduler is provisioned with HAD task. Adding a server to T1 launch the HAD_Set-LocalAdminGroups task, but it ends up with error value 21479426267.

So looking at the  the scheduled task for the PS script location, the c:\Window\HardenAD\ScheduledTasks folder only contains HAD_Delete_Powershell_Logs.

Is there any action to do in order to push the scripts on the server ?

**Expected behavior**
Set-LocalAdminGroups folder should be provisionned with it Powershell Script

**server**
Windows Server 2022 with desktop
Forest and domain level : windows server 2016

**Comment by LoicVeirman** [comment]
Hi,

You should not use the Main branch repository which may contains unstable code.
Please use the package (2.9.8 with QuickFix as of today).

Rgds,
Loic.

De : jmthia ***@***.***>
Date : jeudi, 4 juillet 2024 à 09:52
À : LoicVeirman/HardenAD ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [LoicVeirman/HardenAD] scheduled task not présent (Issue #118)

CAUTION: This email originated from outside your organization. Exercise caution when opening attachments or clicking links, especially from unknown senders.

Describe the bug
I am using the master branch of Harden AD, in order to use GUI task sequence selector. After running all sequence except AD functionnel level, administration account, laps and activated AHD-TS-local-admin-groups, HAD-TS-Reset-computer-sddl.
The task scheduler is provisioned with HAD task. Adding a server to T1 launch the HAD_Set-LocalAdminGroups task, but it ends up with error value 21479426267.

So looking at the the scheduled task for the PS script location, the c:\Window\HardenAD\ScheduledTasks folder only contains HAD_Delete_Powershell_Logs.

Is there any action to do in order to push the scripts on the server ?

Expected behavior
Set-LocalAdminGroups folder should be provisionned with it Powershell Script

server
Windows Server 2022 with desktop
Forest and domain level : windows server 2016

**Comment by jmthia** [comment]
Hi Loïc,
Using the release package, after removing all GPO and scheduled task on DC. I reran HardenAD.ps1. After enabling the HAD-TS-Local-admins-groups GPO on DC, the scripts was not copied in c:\windows\hardenAD\... 
Looking at gpresult, I found that the scripts are imported at startup which means computer reboot. Et voilà !

Regards
Jean Marie
